[tool.ruff]
# Enable pycodestyle (PEP 8) rules
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflake8
    "I",  # isort
    "B",  # flake8-bugbear
    "C",  # flake8-comprehensions
    "A",  # flake8-builtins
    "N",  # pep8-naming
    "UP", # pyupgrade
    "YTT", # flake8-2020
    "RUF", # ruff-specific rules
]

# Disable specific rules
ignore = [
    "E501",  # line too long
    "E203",  # whitespace before ':' (conflicts with black)
    "N802",  # function name should be lowercase
    "N803",  # argument name should be lowercase
    "N806",  # variable in function should be lowercase
]

# Line length
line-length = 88

# Exclude files
exclude = [
    ".git",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    "__pycache__",
    "build",
    "dist",
    "venv",
    "*.pyi",
]

[tool.ruff.isort]
known-first-party = ["evoprompt"]
src = ["evoprompt", "examples"]
