[lint]
select = [
    # Error checking
    "E",  # Pycodestyle errors
    "F",  # Pyflakes errors
    
    # Style
    "C4",  # Flake8 comprehensions
    "I",   # isort (import sorting)
    "UP",  # pyupgrade (modern Python features)
    "W",   # Pycodestyle warnings
    
    # Best practices
    "B",   # flake8-bugbear
    "A",   # flake8-builtins
    "D",   # pydocstyle (docstrings)
    "TCH", # flake8-type-checking
    "SIM", # flake8-simplify
    "RUF", # Ruff-specific rules
    
    # Complexity
    "C90", # McCabe complexity
    "PLR", # pylint rules
]

# Module size and complexity limits
[lint.ruff]
max-module-lines = 200  # Maximum lines per module
max-class-lines = 200     # Maximum lines per class

# Keep existing ignores but add more reasonable ones
ignore = [
    "E501",  # Line too long (handled by formatter)
    "E203",  # Whitespace before ':' (conflicts with black)
    "N802",  # Function name should be lowercase
    "N803",  # Argument name should be lowercase  
    "N806",  # Variable in function should be lowercase
    "W293",  # Blank line contains whitespace
    "D107",  # Missing docstring in __init__
    "S311",  # Standard pseudo-random generators are not suitable for cryptographic purposes
    "PLR0913",  # Too many arguments
    "PLR2004",  # Magic value used
]

[lint.per-file-ignores]
"tests/*" = ["D"]  # Don't require docstrings in tests
"examples/*" = ["D"]  # Don't require docstrings in examples
"src/*" = ["D"]  # Don't require docstrings in examples

[lint.flake8-bugbear]
extend-immutable-calls = ["frozenset", "tuple"]

[lint.isort]
known-first-party = ["evoprompt"]
combine-as-imports = true
force-sort-within-sections = true
order-by-type = false
lines-after-imports = 2
lines-between-types = 1

# Complexity limits
[lint.mccabe]
max-complexity = 5  # McCabe cyclomatic complexity

[lint.pylint]
max-args = 3        # Maximum number of function arguments
max-locals = 15     # Maximum number of local variables
max-statements = 50 # Maximum number of statements per function
max-branches = 12   # Maximum number of branches per function
max-returns = 4     # Maximum number of return statements
max-attributes = 5  # Maximum number of class attributes

[lint.ruff]
# Enable additional Ruff-specific rules
allow-star-arg-unpacking = false
check-builtin-shadowing = true
check-typed-exception = true
