[lint]
# Lint rules
select = [
    "E",   # Pycodestyle errors
    "F",   # Pyflakes errors
    "C4",  # Flake8 comprehensions
    "I",   # isort (import sorting)
    "UP",  # pyupgrade (modern Python features)
    "W",   # Pycodestyle warnings
    "B",   # flake8-bugbear
    "A",   # flake8-builtins
    "D",   # pydocstyle (docstrings)
    "TCH", # flake8-type-checking
    "SIM", # flake8-simplify
    "RUF", # Ruff-specific rules
    "C90", # McCabe complexity
    "PLR", # pylint rules
]

ignore = [
    "E501",  # Line too long (handled by formatter)
    "E203",  # Whitespace before ':' (conflicts with black)
    "N802",  # Function name should be lowercase
    "N803",  # Argument name should be lowercase  
    "N806",  # Variable in function should be lowercase
    "W293",  # Blank line contains whitespace
    "D107",  # Missing docstring in __init__
    "S311",  # Standard pseudo-random generators are not suitable for cryptographic purposes
    "PLR0913",  # Too many arguments
    "PLR2004",  # Magic value used
]

# Complexity settings
[mccabe]
max-complexity = 5

# isort configuration
[isort]
known-first-party = ["evoprompt"]
combine-as-imports = true
force-sort-within-sections = true
order-by-type = false
lines-after-imports = 2
lines-between-types = 1

# flake8-bugbear configuration
[flake8-bugbear]
extend-immutable-calls = ["frozenset", "tuple"]

# Formatting settings
[format]
line-length = 88
indent-style = "space"
indent-width = 4
quote-style = "double"
