[lint]
max-complexity = 5

# isort configuration
[tool.ruff.isort]
known-first-party = ["evoprompt"]
combine-as-imports = true
force-sort-within-sections = true
order-by-type = false
lines-after-imports = 2
lines-between-types = 1

# flake8-bugbear configuration
[tool.ruff.flake8-bugbear]
extend-immutable-calls = ["frozenset", "tuple"]
